### ISSUE TITLE
Rule IDs with spaces cannot be skipped

### ISSUE THREAD

**Issue by adamjohnson01** [accurics/terrascan#610]
* terrascan version: 1.4.0
* Operating System: Docker and Darwin

### Description

I am trying to skip the following but the rule id has spaces in it so it does not work.

```
	Description    :	Ensure CloudWatch logging is enabled for Route53 hosted zones.
	File           :	route53.tf
	Line           :	66
	Severity       :	MEDIUM
	Rule Name      :	route53LoggingDisabled
	Rule ID        :	AWS.Route53 query logs.Logging.Medium.0574
	Resource Name  :	dns
	Resource Type  :	aws_route53_zone
	Category       :	Logging

	-----------------------------------------------------------------------
```

### What I Did
I added the following to the resource

```
ts:skip=AWS.Route53 query logs.Logging.Medium.0574 Only works with public route53
```

**Comment by fetep** [comment]
Also seeing this behavior. Should we fix the rule skipper to support spaces, or rename policies to not have spaces in their reference_id?

**Comment by MrMickS** [comment]
We are seeing the same issue with rules of the form AC_AWS_078 or AC_AWS_070.

**Comment by kanchwala-yusuf** [comment]
@MrMickS, Can you please share an example of your IaC file with us? Just want to reproduce it on my own?

**Comment by harkirat22** [comment]
@fetep we will  make changes to all such policie's reference ids.

**Comment by nasir-rabbani** [comment]
@adamjohnson01 @MrMickS 

Sorry for causing confusions and the issues, which were due to inconsistency in nomenclature of `reference_id`. With PR #786 we are intending to standardize the Rule IDs.

Even though we have added support for spaces while skipping rule, we highly **recommend everyone to refer newly added `id` instead of `reference_id`** for the scanning or suppressing of specific policy.

Please feel free to re-open this issue if it doesn't work as expected. Thanks.

**Comment by nasir-rabbani** [comment]
> * terrascan version: 1.4.0
> * Operating System: Docker and Darwin
> 
> ### Description
> I am trying to skip the following but the rule id has spaces in it so it does not work.
> 
> ```
> 	Description    :	Ensure CloudWatch logging is enabled for Route53 hosted zones.
> 	File           :	route53.tf
> 	Line           :	66
> 	Severity       :	MEDIUM
> 	Rule Name      :	route53LoggingDisabled
> 	Rule ID        :	AWS.Route53 query logs.Logging.Medium.0574
> 	Resource Name  :	dns
> 	Resource Type  :	aws_route53_zone
> 	Category       :	Logging
> 
> 	-----------------------------------------------------------------------
> ```
> 
> ### What I Did
> I added the following to the resource
> 
> ```
> ts:skip=AWS.Route53 query logs.Logging.Medium.0574 Only works with public route53
> ```

The corresponding `id` for this policy is `AC_AWS_0204`. Please let us know if this works for you.

**Comment by nasir-rabbani** [comment]
> AC_AWS_078

Please use the following corresponding `id` values:

`AC_AWS_0497` instead of AC_AWS_078
`AC_AWS_0480` instead of AC_AWS_070

Please confirm if this solves your purpose.

**Comment by sarahc23** [comment]
Hi there, we're having a similar issue. We're trying to suppress AC_AWS_0320, whose [id field has the same name](https://github.com/accurics/terrascan/blob/7d20723c557cb9ab3a64620b1ef886ea7e0cd2bc/pkg/policies/opa/rego/aws/aws_security_group/AC_AWS_0320.json#L17).

We've tried
```
#ts:skip=AC_AWS_0320 Allow SSH
```
and also
```
#ts:skip=networkPort22ExposedToprivate Allow SSH
```
just for good measure, but neither worked.

As a shot in the dark, terrascan flagged the issue inside an `aws_security_group_rule` so that's where we placed the comment. Is this supposed to go inside an `aws_security_group` resource instead?

**Comment by nasir-rabbani** [comment]
@sarahc23 

It would be better for us to understand if you could please attach some reference of where exactly you are putting the comment. 

We need to put the comment `inside the resource block` which is violating the policy.  Refer [this](https://github.com/accurics/terrascan/blob/aaacce22e87635bd69ee042224d6a92e74bc07e1/test/e2e/test_data/iac/resource_skipping/terraform/main.tf#L56). 

Do let us know if this helped.
